import turtle
x,y = eval(input('Enter the (x,y) coordinates for center of the rectangle:'))
w = eval(input("Enter width:"))
h = eval(input("Enter height:"))
turtle.penup()
turtle.goto(x,y)
turtle.left(90)
turtle.forward(h/2)
turtle.left(90)
turtle.pendown()
turtle.forward(w/2)
turtle.left(90)
turtle.forward(h)
turtle.left(90)
turtle.forward(w)
turtle.left(90)
turtle.forward(h)
turtle.left(90)
turtle.forward(w/2)
turtle.done()